# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HU_project
                                 A QGIS plugin
 HU tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-07
        git sha              : $Format:%H$
        copyright            : (C) 2024 by MV
        email                : m.vincent@nca.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .HU_tools_dialog import HU_projectDock
import os.path
from PyQt5.QtWebEngineWidgets import QWebEngineView
from qgis.core import QgsApplication
from qgis.core import QgsMessageLog, Qgis
from .OutilsDivers.provider_edv import ProviderEDV
from .OutilsDivers.Provider_Synthese_champs import Provider_synthese_champsEDV
from .OutilsDivers.Provider_PresentationSIG import Provider_presentationSIG
from .OutilsDivers.Provider_Save_styles import Provider_EnregistrerStylesCouches
from .OutilsDivers.Provider_LiaisonMiniCana import Provider_liaisonminicana
from .OutilsDivers.Provider_syntheseterrain_sdgep import Provider_SyntheseTerrain_sdgep
from .OutilsDivers.Provider_phase1_CreationTablo_Etat_Initial_v28 import Provider_phase1_CreationTablo_EI


class HU_project:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.provider_edv = None
        self.Provider_Synthese_champs = None
        self.Provider_PresentationSIG = None
        self.Provider_Save_styles = None
        self.Provider_LiaisonMiniCana = None
        self.Provider_syntheseterrain_sdgep = None
        #self.Provider_phase1_CreationTablo_Etat_Initial_v28 = None
        
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'HU_project_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&HU_project')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        # Initialize dialog
        #self.dlg = HU_projectDock()
        self.dlg = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('HU_project', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action
        
    def initProcessing(self):
        """Initialise le provider EDV."""
        try:
            # Évite les doublons si déjà enregistré
            if self.provider_edv is None:
                self.provider_edv = ProviderEDV()
                QgsApplication.processingRegistry().addProvider(self.provider_edv)
                QgsMessageLog.logMessage("Provider EDV chargé avec succès ", 'HU_tools', level=Qgis.Info)
            else:
                QgsMessageLog.logMessage("Provider EDV déjà chargé.", 'HU_tools', level=Qgis.Info)
                
            # Initialisation du provider Synthèse Champs
            if self.Provider_Synthese_champs is None:
                self.Provider_Synthese_champs = Provider_synthese_champsEDV()
                QgsApplication.processingRegistry().addProvider(self.Provider_Synthese_champs)
                QgsMessageLog.logMessage("Provider Synthèse Champs chargé avec succès.", 'HU_tools', level=Qgis.Info)
            else:
                QgsMessageLog.logMessage("Provider Synthèse Champs déjà chargé.", 'HU_tools', level=Qgis.Info)
                
            # Initialisation du provider PrésentationSIG
            if self.Provider_PresentationSIG is None:
                self.Provider_PresentationSIG = Provider_presentationSIG()
                QgsApplication.processingRegistry().addProvider(self.Provider_PresentationSIG)
                QgsMessageLog.logMessage("Provider PrésentationSIG chargé avec succès.", 'HU_tools', level=Qgis.Info)
            else:
                QgsMessageLog.logMessage("Provider PrésentationSIG déjà chargé.", 'HU_tools', level=Qgis.Info)
                
            # Initialisation du provider EnregistrerStylesCouches
            if self.Provider_Save_styles is None:
                self.Provider_Save_styles = Provider_EnregistrerStylesCouches()
                QgsApplication.processingRegistry().addProvider(self.Provider_Save_styles)
                QgsMessageLog.logMessage("Provider EnregistrerStylesCouches chargé avec succès.", 'HU_tools', level=Qgis.Info)
            else:
                QgsMessageLog.logMessage("Provider EnregistrerStylesCouches déjà chargé.", 'HU_tools', level=Qgis.Info)
                
            # Initialisation du provider LiaisonMinicana
            if self.Provider_LiaisonMiniCana is None:
                self.Provider_LiaisonMiniCana = Provider_liaisonminicana()
                QgsApplication.processingRegistry().addProvider(self.Provider_LiaisonMiniCana)
                QgsMessageLog.logMessage("Provider LiaisonMinicana chargé avec succès.", 'HU_tools', level=Qgis.Info)
            else:
                QgsMessageLog.logMessage("Provider LiaisonMinicana déjà chargé.", 'HU_tools', level=Qgis.Info)
            
            # Initialisation du provider syntheseterrain_sdgep
            if self.Provider_syntheseterrain_sdgep is None:
                self.Provider_syntheseterrain_sdgep = Provider_SyntheseTerrain_sdgep()
                QgsApplication.processingRegistry().addProvider(self.Provider_syntheseterrain_sdgep)
                QgsMessageLog.logMessage("Provider syntheseterrain_sdgep chargé avec succès.", 'HU_tools', level=Qgis.Info)
            else:
                QgsMessageLog.logMessage("Provider syntheseterrain_sdgep déjà chargé.", 'HU_tools', level=Qgis.Info)

            # Initialisation du provider Phase1_creationtablo_etat_initial_v28
            #if self.Provider_phase1_CreationTablo_Etat_Initial_v28 is None:
            #    self.Provider_phase1_CreationTablo_Etat_Initial_v28 = Provider_phase1_CreationTablo_EI()
            #    QgsApplication.processingRegistry().addProvider(self.Provider_phase1_CreationTablo_Etat_Initial_v28)
            #    QgsMessageLog.logMessage("Provider Phase1_creationtablo_etat_initial_v28 chargé avec succès.", 'HU_tools', level=Qgis.Info)
            #else:
            #    QgsMessageLog.logMessage("Provider Phase1_creationtablo_etat_initial_v28 déjà chargé.", 'HU_tools', level=Qgis.Info)

        except Exception as e:
            QgsMessageLog.logMessage(f"Erreur lors du chargement des providers EDV, PrésentationSIG et EnregistrerStylesCouches : {e}", 'HU_tools', level=Qgis.Critical)

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        
        # Enregistre le provider une seule fois
        self.initProcessing()

        icon_path = ':/plugins/HU_tools/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'HU_project'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.first_start = True

    def unload(self):
        """Supprime le menu, les icônes et les providers du plugin"""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&HU_project'), action)
            self.iface.removeToolBarIcon(action)

        # Supprime proprement le provider si toujours valide
        try:
            if self.provider_edv is not None:
                if QgsApplication.processingRegistry().providerById(self.provider_edv.id()):
                    QgsApplication.processingRegistry().removeProvider(self.provider_edv)
                    QgsMessageLog.logMessage("Provider EDV retiré du registre.", 'HU_tools', level=Qgis.Info)
                else:
                    QgsMessageLog.logMessage("Provider EDV déjà retiré par QGIS.", 'HU_tools', level=Qgis.Warning)
        except RuntimeError:
            QgsMessageLog.logMessage("Provider EDV déjà détruit (ignore).", 'HU_tools', level=Qgis.Warning)

        self.provider_edv = None
        
        #  Retrait du provider Synthèse Champs 
        try:
            if self.Provider_Synthese_champs is not None:
                if QgsApplication.processingRegistry().providerById(self.Provider_Synthese_champs.id()):
                    QgsApplication.processingRegistry().removeProvider(self.Provider_Synthese_champs)
                    QgsMessageLog.logMessage("Provider Synthèse Champs retiré du registre.", 'HU_tools', level=Qgis.Info)
                else:
                    QgsMessageLog.logMessage("Provider Synthèse Champs déjà retiré par QGIS.", 'HU_tools', level=Qgis.Warning)
        except RuntimeError:
            QgsMessageLog.logMessage("Provider Synthèse Champs déjà détruit (ignore).", 'HU_tools', level=Qgis.Warning)
  
        self.Provider_Synthese_champs = None
        
        #  Retrait du provider PrésentationSIG 
        try:
            if self.Provider_PresentationSIG is not None:
                if QgsApplication.processingRegistry().providerById(self.Provider_PresentationSIG.id()):
                    QgsApplication.processingRegistry().removeProvider(self.Provider_PresentationSIG)
                    QgsMessageLog.logMessage("Provider PrésentationSIG retiré du registre.", 'HU_tools', level=Qgis.Info)
                else:
                    QgsMessageLog.logMessage("Provider PrésentationSIG déjà retiré par QGIS.", 'HU_tools', level=Qgis.Warning)
        except RuntimeError:
            QgsMessageLog.logMessage("Provider PrésentationSIG déjà détruit (ignore).", 'HU_tools', level=Qgis.Warning)
  
        self.Provider_PresentationSIG = None
        
        #  Retrait du provider EnregistrerStyles 
        try:
            if self.Provider_Save_styles is not None:
                if QgsApplication.processingRegistry().providerById(self.Provider_Save_styles.id()):
                    QgsApplication.processingRegistry().removeProvider(self.Provider_Save_styles)
                    QgsMessageLog.logMessage("Provider EnregistrerStyles retiré du registre.", 'HU_tools', level=Qgis.Info)
                else:
                    QgsMessageLog.logMessage("Provider PrésentationSIG déjà retiré par QGIS.", 'HU_tools', level=Qgis.Warning)
        except RuntimeError:
            QgsMessageLog.logMessage("Provider EnregistrerStyles déjà détruit (ignore).", 'HU_tools', level=Qgis.Warning)
  
        self.Provider_Save_styles = None
        
        #  Retrait du provider LiaisonMinicana 
        try:
            if self.Provider_LiaisonMiniCana is not None:
                if QgsApplication.processingRegistry().providerById(self.Provider_LiaisonMiniCana.id()):
                    QgsApplication.processingRegistry().removeProvider(self.Provider_LiaisonMiniCana)
                    QgsMessageLog.logMessage("Provider LiaisonMinicana retiré du registre.", 'HU_tools', level=Qgis.Info)
                else:
                    QgsMessageLog.logMessage("Provider LiaisonMinicana déjà retiré par QGIS.", 'HU_tools', level=Qgis.Warning)
        except RuntimeError:
            QgsMessageLog.logMessage("Provider LiaisonMinicana déjà détruit (ignore).", 'HU_tools', level=Qgis.Warning)
  
        self.Provider_LiaisonMiniCana = None
        
        #  Retrait du provider SyntheseTerrain_sdgep 
        try:
            if self.Provider_syntheseterrain_sdgep is not None:
                if QgsApplication.processingRegistry().providerById(self.Provider_syntheseterrain_sdgep.id()):
                    QgsApplication.processingRegistry().removeProvider(self.Provider_syntheseterrain_sdgep)
                    QgsMessageLog.logMessage("Provider syntheseterrain_sdgep retiré du registre.", 'HU_tools', level=Qgis.Info)
                else:
                    QgsMessageLog.logMessage("Provider syntheseterrain_sdgep déjà retiré par QGIS.", 'HU_tools', level=Qgis.Warning)
        except RuntimeError:
            QgsMessageLog.logMessage("Provider syntheseterrain_sdgep déjà détruit (ignore).", 'HU_tools', level=Qgis.Warning)
  
        self.Provider_syntheseterrain_sdgep = None
        
        #  Retrait du provider Phase1_creationtablo_etat_initial_v28 
        #try:
        #    if self.Provider_phase1_CreationTablo_Etat_Initial_v28 is not None:
        #        if QgsApplication.processingRegistry().providerById(self.Provider_phase1_CreationTablo_Etat_Initial_v28.id()):
        #            QgsApplication.processingRegistry().removeProvider(self.Provider_phase1_CreationTablo_Etat_Initial_v28)
        #            QgsMessageLog.logMessage("Provider Provider_phase1_CreationTablo_Etat_Initial_v28 retiré du registre.", 'HU_tools', level=Qgis.Info)
        #        else:
        #            QgsMessageLog.logMessage("Provider Provider_phase1_CreationTablo_Etat_Initial_v28 déjà retiré par QGIS.", 'HU_tools', level=Qgis.Warning)
        #except RuntimeError:
        #    QgsMessageLog.logMessage("Provider Provider_phase1_CreationTablo_Etat_Initial_v28 déjà détruit (ignore).", 'HU_tools', level=Qgis.Warning)
  
        #self.Provider_phase1_CreationTablo_Etat_Initial_v28 = None
        

    def run(self):
        """Run method that performs all the real work"""

        # Crée le dock s'il n'existe pas encore
        if self.dlg is None:
            self.dlg = HU_projectDock(self.iface.mainWindow(), self.iface)
            self.iface.addDockWidget(QtCore.Qt.RightDockWidgetArea, self.dlg)

        # Affiche le dock (sans raise_)
        self.dlg.show()



