# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HU_project
                                 A QGIS plugin
 HU tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-07
        copyright            : (C) 2024 by MV
        email                : m.vincent@nca.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HU_project class from file HU_project.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .HU_tools import HU_project
    return HU_project(iface)
